stuff

diff --git a/scan b/scan
--- a/scan
+++ b/scan
@@ -1,42 +1,94 @@
 #!/bin/bash
 
-ports=-p21,22,23,5380,443,445,995,1723,2075,2076,3000,3306,3868,4443,5443,5900,6443,7443,8080,8888,8443,9091,9443
+while (( "$#" )); do
+	case "$1" in
+    	-t|--target)
+			if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+        		TARGET=$2
+        		shift 2
+      		else
+        		echo "Error: Argument for $1 is missing" >&2
+        		exit 1
+      		fi
+      	;;
+		-f|--file)
+      		if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+        		TARGET_FILE=$2
+				shift 2
+			else
+				echo "Error: Argument for $1 is missing" >&2
+				exit 1
+			fi
+		;;
+		-p|--ports)
+			if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+				ADDITIONAL_PORTS=$2
+				shift 2
+			else
+				echo "Error: Argument for $1 is missing" >&2
+				exit 1
+			fi
+		;;
+		-*|--*=) # unsupported flags
+				echo "Error: Unsupported flag $1" >&2
+			exit 1
+		;;
+	esac
+done
 
-escaped_cidr=$(echo $1 | tr '/' '_')
-hostsfile=$(echo $escaped_cidr)_hosts.txt
-masscanfile=$(echo $escaped_cidr)_masscan.json
-nmapoutfile=$(echo $escaped_cidr)_nmap.xml
+scan_target() {
+	escaped_cidr=$(echo $1 | tr '/' '_')
+	hostsfile=$(echo $escaped_cidr)_hosts.txt
+	masscanfile=$(echo $escaped_cidr)_masscan.json
+	nmapoutfile=$(echo $escaped_cidr)_nmap.xml
 
-mkdir $escaped_cidr
-cd $escaped_cidr
+	mkdir $escaped_cidr 2>/dev/null
+	cd $escaped_cidr
 
-datestamp=$(date +%Y%m%d)
-mkdir $datestamp
-cd $datestamp
+	datestamp=$(date +%Y%m%d)
+	mkdir $datestamp 2>/dev/null
+	cd $datestamp
 
-if [ $# -eq 0 ]; 
+	sudo masscan $ports $1 --output-format json --output-file $masscanfile
+
+	cat $masscanfile | jq .[].ip | sort | uniq | tr -d '"' > $hostsfile
+	host_count=$(wc -l $hostsfile | awk '{print $1}')
+	echo "masscan found $host_count host(s)"
+
+	if [[ $host_count > 0 ]]
+	then
+		ports=$(cat $masscanfile | jq .[].ports[].port | sort | uniq | tr '\n' ',')
+		ports=${ports::-1}
+
+		sudo nmap -O -sSVC -p $ports -iL $hostsfile -oX $nmapoutfile --webxml
+	fi
+
+	rm $hostsfile
+}
+
+if [[ -z $TARGET && -z $TARGET_FILE ]];
 then
-    echo "USAGE: scan <cidr_or_ip> <additional_ports>"
+    echo "USAGE: scan [-t <cidr_or_ip>|-f <targets_file>] [-p <additional_ports>]"
+	echo "No targets provided" >&2
     exit 1
 fi
 
-if [[ $2 ]]
+ports=-p21,22,23,80,81,139,443,445,995,1433,1723,2075,2076,2083,2375,3000,3306,3868,4443,5380,5443,5900,6443,7443,8069,8080,8880,1900,8443,9000,9091,9200,9443,10000,10250
+
+echo "Default Ports: $ports"
+if [[ $ADDITIONAL_PORTS ]]
 then
-	ports=$ports,$2
+	echo "Additional Ports: $ADDITIONAL_PORTS"
+	ports=$ports,$ADDITIONAL_PORTS
 fi
 
-sudo masscan -v $ports $1 --output-format json --output-file $masscanfile
-
-cat $masscanfile | jq .[].ip | sort | uniq | tr -d '"' > $hostsfile
-host_count=$(wc -l $hostsfile | awk '{print $1}')
-echo "masscan found $host_count host(s)"
-
-if [[ $host_count > 0 ]]
+if [ -n $TARGET ];
 then
-	ports=$(cat $masscanfile | jq .[].ports[].port | sort | uniq | tr '\n' ',')
-	ports=${ports::-1}
-
-	sudo nmap -O -sSVC -p $ports -iL $hostsfile -oX $nmapoutfile --webxml
+	scan_target $TARGET
+else
+	for target in $(cat $TARGET_FILE)
+	do
+		scan_target $target
+		cd ../..
+	done
 fi
-
-rm $hostsfile
